version: '3'

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

services:

  web:
    image: carlhat/server-app:latest
    ports:
      - "8000:8000"
    deploy:
     resources:
        limits:
          cpus: '0.25'
          memory: 256M
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    deploy:
     resources:  
        limits:
          cpus: '0.25'
          memory: 256M

  visualizer:
    image: zhijiewang22/visualizer
    ports:
      - "5000:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    command: "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alert-rules.yml:/etc/prometheus/alert-rules.yml:ro
      - ./prometheus-data:/prometheus
    deploy:
      placement:
        constraints: [node.role == manager]

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    deploy:
      placement:
        constraints: [node.role == manager]

  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    deploy:
      placement:
        constraints: [node.role == manager]

  scaler:
    image: carlhat/my-scaler:latest
    ports:
      - "5001:5001"
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
      placement:
        constraints: [node.role == manager]