groups:
- name: web_response
  rules:
  - alert: HighResponseTime
    expr: rate(request_processing_seconds_sum[20s]) / rate(request_processing_seconds_count[20s]) > 5
    annotations:
      summary: High response time
  - alert: LowResponseTime
    expr: rate(request_processing_seconds_sum[20s]) / rate(request_processing_seconds_count[20s]) < 2 or absent(rate(request_processing_seconds_count[30s]))
    annotations:
      summary: Low response time