global:
  scrape_interval:     15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - app_name_alertmanager:9093

rule_files:
  - "/etc/prometheus/alert-rules.yml"

scrape_configs:
  - job_name: 'server_app'
    scrape_interval: 5s
    static_configs:
      - targets: ['app_name_web:8000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['app_name_node_exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['app_name_cadvisor:8080']