global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - app_name_alertmanager:9093

rule_files:
  - "/etc/prometheus/alert-rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'server_app'
    # Override the global default and scrape targets from this job every 5 seconds.
    static_configs:
      - targets: ['app_name_web:8000']

  # Example job for node_exporter
  # - job_name: 'node_exporter'
  #   static_configs:
  #     - targets: ['node_exporter:9100']

  # Example job for cadvisor
  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['cadvisor:8080']