global:
  scrape_interval:     15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - app_name_alertmanager:9093

rule_files:
  - "/etc/prometheus/alert-rules.yml"

scrape_configs:
  - job_name: 'server_app'
    dns_sd_configs:
      - names:
          - 'app_name_web'
        type: 'A'
        port: 8000
    relabel_configs:
      - source_labels: [__address__, '__meta_dns_name']
        separator: ';'
        target_label: instance
        replacement: '${1};${2}'

  # - job_name: 'node_exporter'
  #   static_configs:
  #     - targets: ['app_name_node_exporter:9100']

  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['app_name_cadvisor:8080']

  # - job_name: 'dockerd_exporter '
  #   dns_sd_configs:
  #     - names:
  #         - 'app_name_dockerd_exporter'
  #       type: 'A'
  #       port: 9323